### ISSUE TITLE
Clearing mobile delay leads to lock loop

### ISSUE THREAD

**Issue by leoccyao** [ericbiewener/obsidian-lock-screen-plugin#3]
On Obsidian Mobile, clearing the "delay before showing lock screen" (which is a sensible thing to do while setting a new delay) causes the delay to be set to 0, which leads to the lock screen instantly appearing, and constantly reappearing immediately after going through it. This causes the vault (and by extension the app) to be completely unusable until either the plugin files in `.obsidian` are modified (which itself is hard to access on iOS), or the vault is deleted (not very user friendly).

Setting a delay of 0 makes sense on desktop, to have the lock screen instantly show upon unfocus. However, I think this should be explicitly disallowed on mobile.

Obsidian Mobile for iOS v1.0.5

**Comment by ericbiewener** [comment]
Thanks. I've separated the timeout settings now so that a different one can be set for desktop vs. mobile, and on mobile it will never set the timeout to less than 5 seconds (added messaging in the settings tab to that effect). See https://github.com/ericbiewener/obsidian-lock-screen-plugin/commit/9e95183d3ff38a7da41de2e609ff9e6320034e87
